### ISSUE TITLE
google.auth.exceptions.DefaultCredentialsError: File key.json was not found.

### ISSUE THREAD

**Issue by osvimer** [lightningorb/chatJeepTea#3]
❯ python src/main.py
INFO:telegram.ext._application:Application started
Error while checking authorization: [Errno 2] No such file or directory: 'src/auth.json'
INFO:speak:Synthesizing into text: Hello and welcome to Chat Jeep Tea. To speak to me, record and send a voice message by doing a long press on the microphone icon at the bottom right of telegram. I will respond to your message. To bring up the help menu at any time, type /help. Please bear in mind I keep a certain (somewhat small) amount of the conversation history as context. This helps us have a more natural conversation. Go ahead, ask me anything.
INFO:speak:Language: en-US
ERROR:telegram.ext._application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/anonymous/git/chatJeepTea/.venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/Users/anonymous/git/chatJeepTea/.venv/lib/python3.11/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anonymous/git/chatJeepTea/src/main.py", line 63, in intro
    fn = await speak(msg, user.id, "en-US")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anonymous/git/chatJeepTea/src/speak.py", line 28, in speak
    response = await loop.run_in_executor(None, synthesize_speech)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anonymous/git/chatJeepTea/src/speak.py", line 17, in synthesize_speech
    client = texttospeech.TextToSpeechClient()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anonymous/git/chatJeepTea/.venv/lib/python3.11/site-packages/google/cloud/texttospeech_v1/services/text_to_speech/client.py", line 431, in __init__
    self._transport = Transport(
                      ^^^^^^^^^^
  File "/Users/anonymous/git/chatJeepTea/.venv/lib/python3.11/site-packages/google/cloud/texttospeech_v1/services/text_to_speech/transports/grpc.py", line 149, in __init__
    super().__init__(
  File "/Users/anonymous/git/chatJeepTea/.venv/lib/python3.11/site-packages/google/cloud/texttospeech_v1/services/text_to_speech/transports/base.py", line 98, in __init__
    credentials, _ = google.auth.default(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/Users/anonymous/git/chatJeepTea/.venv/lib/python3.11/site-packages/google/auth/_default.py", line 615, in default
    credentials, project_id = checker()
                              ^^^^^^^^^
  File "/Users/anonymous/git/chatJeepTea/.venv/lib/python3.11/site-packages/google/auth/_default.py", line 608, in <lambda>
    lambda: _get_explicit_environ_credentials(quota_project_id=quota_project_id),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anonymous/git/chatJeepTea/.venv/lib/python3.11/site-packages/google/auth/_default.py", line 228, in _get_explicit_environ_credentials
    credentials, project_id = load_credentials_from_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anonymous/git/chatJeepTea/.venv/lib/python3.11/site-packages/google/auth/_default.py", line 116, in load_credentials_from_file
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: File key.json was not found.
Error while checking authorization: [Errno 2] No such file or directory: 'src/auth.json'anonymous

**Comment by lightningorb** [comment]
Thanks for your report.

Please create an `src/auth.json` containing a list. The list should be your telegram user id.

I'll check in a fix tomorrow.

**Comment by lightningorb** [comment]
Fixed. If auth.json doesn't exist, it gets created with your user_id.
